### PR TITLE
Hapi 17

### PR DESCRIPTION
**Pull request by orthagonal**

### CODE REVIEW

**Comment by bendrucker** [comment]
Hi there, this looks pretty far from ready. Please check out the failing tests and avoid using async/await. I am not willing to break compatibility for older versions and it looks like you haven’t really made any consideration for that.

**Comment by jgallen23** [comment]
I think it is going to be tough to not break compatibility with older versions and support hapi 17 at the same time.  The whole plugin system has changed in hapi 17 and it needs promises now. I would just suggest releasing a major version of the library and note that 3.x is for hapi 17+ and 2.x is for hapi 16

**Comment by bendrucker** [comment]
Really? I’m not using Hapi day to day but that seems like a huge mistake. I really doubt you can’t make this work. It may be tricky but I’d rather bend over backwards in the library and detect a callback if it’s passed in. And even if the Hapi 17 path uses promises I don’t want async/await.

**Comment by jgallen23** [comment]
Just an FYI: https://github.com/hapijs/hapi/issues/3658.

> At the heart of the v17 release is the replacement of the reply interface (e.g. the reply() method passed to handlers, extensions, and authentication methods) with the new lifecycle method concept. The other major changes are the removal of multi-connections support and domain protection.

> Note: hapi v17 requires node v8 and assumes a high proficiency with recent changes to JS. These notes and the hapi documentation do not go into any details about using async/await and promises as well as other topics such as symbols, sets, default values, etc. It is critical to have a strong understanding of the new flow controls introduced by async/await and the patterns around them before attempting to migrate to this new version.

**Comment by bendrucker** [comment]
Ok, that's super helpful. Figured there was a changelog that went into more detail. I'd rather try to use promises and not break backwards compat. I still think it's possible.

From the looks of that issue, the changes all look like good ideas but the adoption seems slow.

**Pull request closed without merging**
